#!/bin/bash
# AUR-Database Init

onekeyMkdir() {
    if [ ! -f pkglist.txt ]; then
        onekeyUpdateList
    fi
    for ((i_mkdir = 1; i_mkdir <= $(cat pkglist.txt | wc -l); i_mkdir++)); do
        pkgname=$(cat pkglist.txt | awk 'NR=='"$i_mkdir"'{print}')
        save_link="./package/"$(echo $pkgname | cut -c1)"/"$(echo $pkgname | awk -F- '{print $1}')"/"$pkgname
        mkdir -p $save_link
        echo "Y:" $save_link
    done
}

onekeyUpdateList() {
    ./ctl-git-aur --getbranch >pkglist.txt
}

onekeyGetAllPkgCfg() {
    pkg_list="$(cat pkglist.txt)"
    if [ $2 ]; then
        pkg_list=$(echo "$pkg_list" | grep "^$2")
    fi
    for ((i_ga = 1; i_ga <= $(echo "$pkg_list" | wc -l); i_ga++)); do
        pkg_name=$(echo "$pkg_list" | awk 'NR=='"$i_ga"'{print}')
        case "$1" in
        "git")
            onekeyGetOnePkgCfg-Git $pkg_name
            ;;
        "web")
            onekeyGetOnePkgCfg-Web $pkg_name
            ;;
        esac
    done
}

onekeyGetOnePkgCfg-Git() {
    ./ctl-git-aur --setbranch $1
    onekeyGetOnePkgCfg $1 "$(cat ../aur-list/PKGBUILD)"
}

onekeyGetOnePkgCfg-Web() {
    onekeyGetOnePkgCfg $1 "`wget -qO- "https://github.com/opendde/10006-opendde-aur-ci/raw/$1/PKGBUILD"`"
}

onekeyGetOnePkgCfg() {
    file_content="$2"
    var_list="$(echo "$file_content" | grep "=" | grep -v "make " | grep -v "^ " | grep -v "^#")"
    save_link="./package/"$(echo $1 | cut -c1)"/"$(echo $1 | awk -F- '{print $1}')"/"$1"/var.json"
    echo $save_link
    echo '{' >$save_link
    for ((i_var = 1; i_var <= $(echo "$var_list" | wc -l); i_var++)); do
        var=$(echo "$var_list" | awk 'NR=='"$i_var"'{print}')
        var_left=$(echo $var | awk -F= '{print $1}')
        var_right=${var#*=}
        if [ "$(echo $var_right | grep "(")" ]; then
            var_right='['$(echo "$var_right" | sed -e 's#(##g' -e 's#)##g' -e 's# #,#g')']'
        fi
        if [ "$(echo "$var_right" | grep \')" ]; then
            var_right=$(echo "$var_right" | sed -e s?\'?\"?g)
        fi
        #var_right=`echo $var_right|sed -e 's?x86_64?"x86_64"?'`
        #加引号检测
        if [ "$(echo $var_right | grep '^"')" ] || [ "$(echo $var_right | grep -E "[] []+")" ]; then
            var_right=$var_right
        else
            var_right=\"$var_right\"
        fi
        #是否最后一项检测
        if [ $i_var -lt $(echo "$var_list" | wc -l) ]; then
            var_right=$var_right","
        fi
        echo \"$var_left'": '$var_right >>$save_link
    done
    echo '}' >>$save_link
    function_list="$(echo "$file_content" | grep "()" | sed 's#() {##g' | grep -v "^#")"
    for ((i_func = 1; i_func <= $(echo "$function_list" | wc -l); i_func++)); do
        a_function=$(echo "$function_list" | awk 'NR=='"$i_func"'{print}')
        save_link="./package/"$(echo $1 | cut -c1)"/"$(echo $1 | awk -F- '{print $1}')"/"$1"/f_"$(echo $a_function)
        #echo $save_link
        echo "$(echo "$file_content" | sed -n '/'"$a_function"'()/,/^}/p')" >$save_link
    done
}

./ctl-git-aur || exit 1
case "$1" in
"--getallcfg")
    if [ "x$2" = "xgit" ] || [ "x$2" = "xweb" ]; then
        onekeyGetAllPkgCfg $2 $3
    fi
    ;;
"--mkdir-all")
    onekeyMkdir
    ;;
esac
