pkgname=10ff-git
_pkgname=10ff
pkgver=r53.10d48c2
pkgrel=1
pkgdesc="Typing tests in CLI"
arch=("any")
url="https://github.com/rr-/${_pkgname}"
license=("WTFPL")
depends=("python")
makedepends=("git")
source=("git+https://github.com/rr-/${_pkgname}.git")
md5sums=("SKIP")
